/**:
  ros__parameters:
    enable_color: true
    enable_depth: true
    enable_infra1: false
    enable_infra2: false
    enable_gyro: false
    enable_accel: false

    rgb_camera.color_profile: "640,480,30"
    depth_module.depth_profile: "640,480,30"

    align_depth.enable: true
    pointcloud.enable: false
    pointcloud.stream_filter: 2

    initial_reset: true
    publish_tf: true
    tf_publish_rate: 0.0
